-- Decompiled with Potassium's decompiler.

return table.freeze({
    ["Open 1"] = {
        Identifiers = { 83784843438214 },
        Properties = {
            Volume = 1
        }
    },
    ["Open 3"] = {
        Identifiers = { 98790265203165 },
        Properties = {
            Volume = 1
        }
    },
    ["Open 4"] = {
        Identifiers = { 88272495459107 },
        Properties = {
            Volume = 1
        }
    },
    ["Open 5"] = {
        Identifiers = { 74697823020815 },
        Properties = {
            Volume = 1
        }
    },
    ["Open 6"] = {
        Identifiers = { 71653300860732 },
        Properties = {
            Volume = 1
        }
    },
    ["Blue 1"] = {
        Identifiers = { 137928749668582 },
        Properties = {
            Volume = 1
        }
    },
    ["Blue 2"] = {
        Identifiers = { 109885756116522 },
        Properties = {
            Volume = 1
        }
    },
    ["Purple 2"] = {
        Identifiers = { 113620090187082 },
        Properties = {
            Volume = 1
        }
    },
    ["Pink 1"] = {
        Identifiers = { 87694706582785 },
        Properties = {
            Volume = 1
        }
    },
    ["Pink 2"] = {
        Identifiers = { 87118573803632 },
        Properties = {
            Volume = 1
        }
    },
    ["Red 1"] = {
        Identifiers = { 76006526162497 },
        Properties = {
            Volume = 1
        }
    },
    ["Red 2"] = {
        Identifiers = { 110026755943000 },
        Properties = {
            Volume = 1
        }
    },
    ["Gold 1"] = {
        Identifiers = { 81201326843458 },
        Properties = {
            Volume = 1
        }
    },
    ["Gold 3"] = {
        Identifiers = { 71722248343771 },
        Properties = {
            Volume = 1
        }
    },
    ["Purchase 1"] = {
        Identifiers = { 79286539611874 },
        Properties = {
            Volume = 1
        }
    },
    ["Purchase 3"] = {
        Identifiers = { 97469251711564 },
        Properties = {
            Volume = 1
        }
    },
    ["Purchase 4"] = {
        Identifiers = { 74711209048661 },
        Properties = {
            Volume = 1
        }
    },
    ["Purchase 5"] = {
        Identifiers = { 127941415082968 },
        Properties = {
            Volume = 1
        }
    },
    ["Purchase 6"] = {
        Identifiers = { 126668136075373 },
        Properties = {
            Volume = 1
        }
    },
    ["Declined 1"] = {
        Identifiers = { 70483060330147 },
        Properties = {
            Volume = 1
        }
    },
    ["Declined 2"] = {
        Identifiers = { 79659680666014 },
        Properties = {
            Volume = 1
        }
    },
    ["Declined 3"] = {
        Identifiers = { 85952359766093 },
        Properties = {
            Volume = 1
        }
    },
    ["Declined 5"] = {
        Identifiers = { 118817211824941 },
        Properties = {
            Volume = 1
        }
    },
    ["Refresh 1"] = {
        Identifiers = { 118589137824364 },
        Properties = {
            Volume = 1
        }
    },
    ["Refresh 2"] = {
        Identifiers = { 114417795379125 },
        Properties = {
            Volume = 1
        }
    },
    ["Refresh 3"] = {
        Identifiers = { 137361925270759 },
        Properties = {
            Volume = 1
        }
    },
    ["Refresh 4"] = {
        Identifiers = { 97936190208247 },
        Properties = {
            Volume = 1
        }
    },
    ["Refresh 5"] = {
        Identifiers = { 112269907916840 },
        Properties = {
            Volume = 1
        }
    },
    ["Refresh 6"] = {
        Identifiers = { 105230581706812 },
        Properties = {
            Volume = 1
        }
    },
    ["Discontinued 1"] = {
        Identifiers = { 126114785207573 },
        Properties = {
            Volume = 1
        }
    },
    ["Discontinued 2"] = {
        Identifiers = { 123592995001713 },
        Properties = {
            Volume = 1
        }
    },
    ["Discontinued 3"] = {
        Identifiers = { 99448227060185 },
        Properties = {
            Volume = 1
        }
    }
});