-- Decompiled with Potassium's decompiler.

return table.freeze({
    ["Fall Damage"] = {
        Identifiers = { 96077875667242 },
        Properties = {
            RollOffMaxDistance = 90,
            RollOffMinDistance = 2,
            Volume = 1
        }
    },
    ["Character Killed"] = {
        Identifiers = { 79494830572923 },
        Properties = {
            RollOffMaxDistance = 90,
            RollOffMinDistance = 10,
            Volume = 2.25
        }
    },
    ["Character Death Grunt"] = {
        Identifiers = { 94141667493613, 75636280774479, 73096326509225 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 1
        }
    },
    ["Character Damaged"] = {
        Identifiers = { 99240460301381, 101859383657555, 139730338159040, 72794099968301 },
        Properties = {
            RollOffMaxDistance = 90,
            RollOffMinDistance = 10,
            Volume = 1
        }
    }
});