-- Decompiled with Potassium's decompiler.

return table.freeze({
    Fling = {
        Identifiers = { 132325238600961 },
        Properties = {
            Volume = 1,
            Persistent = true
        }
    },
    Gold = {
        Identifiers = { 73489888903401 },
        Properties = {
            Volume = 1
        }
    },
    LeSunshine = {
        Identifiers = { 113717841113057 },
        Properties = {
            Volume = 1.5,
            Persistent = true
        }
    }
});