-- Decompiled with Potassium's decompiler.

return table.freeze({
    ["Countdown Timer"] = {
        Identifiers = { 100963371018337 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Settings Click"] = {
        Identifiers = { 72315850035802 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Inventory Click"] = {
        Identifiers = { 111207632919524 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Play Click"] = {
        Identifiers = { 91816417148938 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Dashboard Click"] = {
        Identifiers = { 93054950840645 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Loadout Click"] = {
        Identifiers = { 86919772875161 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Store Click"] = {
        Identifiers = { 86919772875161 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Gamemodes Click"] = {
        Identifiers = { 86919772875161 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Highlight"] = {
        Identifiers = { 128542537508033 },
        Properties = {
            Volume = 0.5
        }
    },
    ["UI Click"] = {
        Identifiers = { 86919772875161 },
        Properties = {
            Volume = 0.5
        }
    },
    ["Successful Buy Menu Purchase"] = {
        Identifiers = { 134998174688363 },
        Properties = {
            Volume = 0.5
        }
    },
    ["New Item Reveal"] = {
        Identifiers = { 92737314376950 },
        Properties = {
            Volume = 0.5
        }
    },
    ["TradeUp Contract Slide"] = {
        Identifiers = { 139279533555596 },
        Properties = {
            Volume = 0.5
        }
    },
    ["TradeUp Approved"] = {
        Identifiers = { 105067129475591 },
        Properties = {
            Volume = 1
        }
    },
    ["TradeUp Type 1"] = {
        Identifiers = { 99439656617348 },
        Properties = {
            Volume = 0.5
        }
    },
    ["TradeUp Type 2"] = {
        Identifiers = { 106193435474495 },
        Properties = {
            Volume = 0.5
        }
    },
    ["TradeUp Type 3"] = {
        Identifiers = { 90998900151715 },
        Properties = {
            Volume = 0.5
        }
    },
    ["Notification Error"] = {
        Identifiers = { 84091803404257 },
        Properties = {
            Volume = 0.5
        }
    },
    ["Notification Success"] = {
        Identifiers = { 98360775959854 },
        Properties = {
            Volume = 0.5
        }
    },
    ["Mission Completed"] = {
        Identifiers = { 89062677258924 },
        Properties = {
            Volume = 3
        }
    },
    ["XP Bar Fill"] = {
        Identifiers = { 119205674023715 },
        Properties = {
            Volume = 0.75
        }
    },
    ["Level Up"] = {
        Identifiers = { 0 },
        Properties = {
            Volume = 0.75
        }
    }
});