-- Decompiled with Potassium's decompiler.

return {
    Range1 = {
        audioId = "rbxassetid://92533051884274",
        text = "Hello, trainee! Welcome to the training facility!"
    },
    Range2 = {
        audioId = "rbxassetid://82891628238715",
        text = "Step forward into the shooting range!"
    },
    Range3 = {
        audioId = "rbxassetid://133857824137736",
        text = "Using the Buy menu, purchase an AK-47."
    },
    RangePractice = {
        audioId = "rbxassetid://97546618118367",
        text = "Shoot and reload your AK-47."
    },
    Range4 = {
        audioId = "rbxassetid://128670887782306",
        text = "Good! Beware! Targets will now spawn!"
    },
    Range5 = {
        audioId = "rbxassetid://135990946612536",
        text = "Using your weapons, let\'s take these dummies out!"
    },
    Range6 = {
        audioId = "rbxassetid://117092268069414",
        text = "Great job, soldier! Remember, you need to stand still to be accurate with your guns. Let\'s head over and learn about the two different teams!"
    },
    Learn1 = {
        audioId = "rbxassetid://94886565731047",
        text = "You can play as either terrorists or counter-terrorists. The terrorists attack and the counter-terrorists defend."
    },
    Learn2 = {
        audioId = "rbxassetid://73904670409558",
        text = "Right now, you are a terrorist, and these are your teammates. As a terrorist, your job each round is to kill all the counter-terrorists. Or you can plant the bomb and defend it until it explodes.",
        pages = { "Right now, you are a terrorist, and these are your teammates.", "As a terrorist, your job each round is to kill all the counter-terrorists. Or you can plant the bomb and defend it until it explodes." }
    },
    Learn3 = {
        audioId = "rbxassetid://95235285044507",
        text = "Follow your teammates into the next room."
    },
    Bomb1 = {
        audioId = "rbxassetid://71655304258170",
        text = "The bomb site is currently empty. Let\'s fix that. Walk over to the indicated bomb planting area."
    },
    Bomb2 = {
        audioId = "rbxassetid://91947374877821",
        text = "Good! Each map usually has two bomb sites. When you\'re on one of these sites, you may plant the bomb."
    },
    Bomb3 = {
        audioId = "rbxassetid://97811457117351",
        text = "Go ahead, try it! But be careful! Don\'t let the other team spot ya!"
    },
    Bomb4 = {
        audioId = "rbxassetid://131164152092223",
        text = "Great job, soldier! You have successfully planted the bomb! But be aware, counter-terrorists are on the way!"
    },
    Bomb5 = {
        audioId = "rbxassetid://70525756011389",
        text = "Watch out! The counter-terrorists are approaching! They will try to defuse the bomb! Protect the bomb site!"
    },
    Bomb7 = {
        audioId = "rbxassetid://127170482229013",
        text = "Great work defending the bomb, soldier!"
    },
    Bomb8 = {
        audioId = "rbxassetid://123169805254461",
        text = "Now, let\'s try putting you onto the counter-terrorist team. Head into the next room."
    },
    BombDefuse1 = {
        audioId = "rbxassetid://93015183703998",
        text = "As a counter-terrorist, your job each round is to defend the bomb sites and kill all the terrorists. If the terrorists manage to plant the bomb, then you must defuse it!",
        pages = { "As a counter-terrorist, your job each round is to defend the bomb sites and kill all the terrorists.", "If the terrorists manage to plant the bomb, then you must defuse it!" }
    },
    BombDefuse2 = {
        audioId = "rbxassetid://84778242690221",
        text = "For this exercise, the terrorists have planted the bomb. Kill all the terrorists.",
        region = { 0, 4.9 }
    },
    BombDefuse2b = {
        audioId = "rbxassetid://84778242690221",
        text = "Defuse the bomb before it explodes!",
        region = { 5.31, 7.35 }
    },
    BombDefuseSuccess = {
        audioId = "rbxassetid://131513472263435",
        text = "Great job, soldier! You are now ready to enter the battlefield!"
    },
    FriendlyKill = {
        audioId = "rbxassetid://86189185225078",
        text = "Don\'t kill your teammates!"
    },
    FriendlyFire = {
        audioId = "rbxassetid://97970666861827",
        text = "Watch your fire! Those are friendlies!"
    },
    RecoilTip = {
        audioId = "rbxassetid://109063859348103",
        text = "Pull down to control your recoil."
    },
    Misc1 = {
        audioId = "rbxassetid://75808534568247",
        text = "Good shot!"
    },
    Misc2 = {
        audioId = "rbxassetid://116852386704512",
        text = "Well done!"
    },
    Misc3 = {
        audioId = "rbxassetid://120349771827126",
        text = "Perfect!"
    }
};