-- Decompiled with Potassium's decompiler.

return table.freeze({
    Equip = {
        Identifiers = { 112207211672543 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 0.5
        }
    },
    HitOne = {
        Identifiers = { 91980681166654 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 1
        }
    },
    HitTwo = {
        Identifiers = { 113877581577512 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 1
        }
    },
    HitThree = {
        Identifiers = { 98261436049971 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 1
        }
    },
    BackStab = {
        Identifiers = { 91382859039642 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 1
        }
    },
    Handling1 = {
        Identifiers = { 79800202848684 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 0.9
        }
    },
    TurnOff = {
        Identifiers = { 80269962013444 },
        Properties = {
            RollOffMaxDistance = 50,
            RollOffMinDistance = 10,
            Volume = 0.9
        }
    }
});