-- Decompiled with Potassium's decompiler.

return {
    Content = {
        Accessory = {
            h = 48,
            w = 48,
            x = 0,
            y = 0
        },
        Actor = {
            h = 48,
            w = 48,
            x = 48,
            y = 0
        },
        AdGui = {
            h = 48,
            w = 48,
            x = 96,
            y = 0
        },
        AdPortal = {
            h = 48,
            w = 48,
            x = 144,
            y = 0
        },
        AirController = {
            h = 48,
            w = 48,
            x = 192,
            y = 0
        },
        Animation = {
            h = 48,
            w = 48,
            x = 384,
            y = 0
        },
        AnimationConstraint = {
            h = 45,
            w = 48,
            x = 240,
            y = 0
        },
        AnimationController = {
            h = 48,
            w = 48,
            x = 288,
            y = 0
        },
        AnimationFromVideoCreatorService = {
            h = 48,
            w = 48,
            x = 336,
            y = 0
        },
        Animator = {
            h = 48,
            w = 48,
            x = 432,
            y = 0
        },
        ArcHandles = {
            h = 48,
            w = 48,
            x = 480,
            y = 0
        },
        Atmosphere = {
            h = 48,
            w = 48,
            x = 528,
            y = 0
        },
        AudioAnalyzer = {
            h = 48,
            w = 48,
            x = 576,
            y = 0
        },
        AudioChorus = {
            h = 48,
            w = 48,
            x = 624,
            y = 0
        },
        AudioCompressor = {
            h = 48,
            w = 48,
            x = 672,
            y = 0
        },
        AudioDeviceInput = {
            h = 48,
            w = 48,
            x = 0,
            y = 48
        },
        AudioDeviceOutput = {
            h = 48,
            w = 48,
            x = 48,
            y = 48
        },
        AudioDistortion = {
            h = 48,
            w = 48,
            x = 96,
            y = 48
        },
        AudioEcho = {
            h = 48,
            w = 48,
            x = 144,
            y = 48
        },
        AudioEmitter = {
            h = 48,
            w = 48,
            x = 192,
            y = 48
        },
        AudioEqualizer = {
            h = 48,
            w = 48,
            x = 240,
            y = 48
        },
        AudioFader = {
            h = 48,
            w = 48,
            x = 288,
            y = 48
        },
        AudioFlanger = {
            h = 48,
            w = 48,
            x = 336,
            y = 48
        },
        AudioListener = {
            h = 48,
            w = 48,
            x = 384,
            y = 48
        },
        AudioPitchShifter = {
            h = 48,
            w = 48,
            x = 432,
            y = 48
        },
        AudioPlayer = {
            h = 48,
            w = 48,
            x = 480,
            y = 48
        },
        AudioReverb = {
            h = 48,
            w = 48,
            x = 528,
            y = 48
        },
        AvatarEditorService = {
            h = 48,
            w = 48,
            x = 576,
            y = 48
        },
        Backpack = {
            h = 48,
            w = 48,
            x = 624,
            y = 48
        },
        BallSocketConstraint = {
            h = 48,
            w = 48,
            x = 672,
            y = 48
        },
        BasePlate = {
            h = 48,
            w = 48,
            x = 0,
            y = 96
        },
        BillboardGui = {
            h = 48,
            w = 48,
            x = 48,
            y = 96
        },
        BindableEvent = {
            h = 48,
            w = 48,
            x = 96,
            y = 96
        },
        BindableFunction = {
            h = 48,
            w = 48,
            x = 144,
            y = 96
        },
        BlockMesh = {
            h = 48,
            w = 48,
            x = 192,
            y = 96
        },
        BloomEffect = {
            h = 48,
            w = 48,
            x = 240,
            y = 96
        },
        BlurEffect = {
            h = 48,
            w = 48,
            x = 288,
            y = 96
        },
        BodyAngularVelocity = {
            h = 48,
            w = 48,
            x = 336,
            y = 96
        },
        BodyColors = {
            h = 48,
            w = 48,
            x = 384,
            y = 96
        },
        BodyForce = {
            h = 48,
            w = 48,
            x = 432,
            y = 96
        },
        BodyGyro = {
            h = 48,
            w = 48,
            x = 480,
            y = 96
        },
        BodyPosition = {
            h = 48,
            w = 48,
            x = 528,
            y = 96
        },
        BodyThrust = {
            h = 48,
            w = 48,
            x = 576,
            y = 96
        },
        BodyVelocity = {
            h = 48,
            w = 48,
            x = 624,
            y = 96
        },
        Bone = {
            h = 48,
            w = 48,
            x = 672,
            y = 96
        },
        BoolValue = {
            h = 48,
            w = 48,
            x = 0,
            y = 144
        },
        BoxHandleAdornment = {
            h = 48,
            w = 48,
            x = 48,
            y = 144
        },
        BrickColorValue = {
            h = 48,
            w = 48,
            x = 96,
            y = 144
        },
        BubbleChatConfiguration = {
            h = 48,
            w = 48,
            x = 144,
            y = 144
        },
        Buggaroo = {
            h = 48,
            w = 48,
            x = 192,
            y = 144
        },
        CFrameValue = {
            h = 48,
            w = 48,
            x = 240,
            y = 144
        },
        Camera = {
            h = 48,
            w = 48,
            x = 288,
            y = 144
        },
        CanvasGroup = {
            h = 48,
            w = 48,
            x = 336,
            y = 144
        },
        CharacterControllerManager = {
            h = 48,
            w = 48,
            x = 384,
            y = 144
        },
        CharacterMesh = {
            h = 48,
            w = 48,
            x = 432,
            y = 144
        },
        Chat = {
            h = 48,
            w = 48,
            x = 576,
            y = 144
        },
        ChatInputBarConfiguration = {
            h = 48,
            w = 48,
            x = 480,
            y = 144
        },
        ChatWindowConfiguration = {
            h = 48,
            w = 48,
            x = 528,
            y = 144
        },
        ChorusSoundEffect = {
            h = 48,
            w = 48,
            x = 624,
            y = 144
        },
        Class = {
            h = 48,
            w = 48,
            x = 672,
            y = 144
        },
        ClickDetector = {
            h = 48,
            w = 48,
            x = 0,
            y = 192
        },
        ClientReplicator = {
            h = 48,
            w = 48,
            x = 48,
            y = 192
        },
        ClimbController = {
            h = 48,
            w = 48,
            x = 96,
            y = 192
        },
        Clouds = {
            h = 48,
            w = 48,
            x = 144,
            y = 192
        },
        Color = {
            h = 48,
            w = 48,
            x = 240,
            y = 192
        },
        ColorCorrectionEffect = {
            h = 48,
            w = 48,
            x = 192,
            y = 192
        },
        CompressorSoundEffect = {
            h = 48,
            w = 48,
            x = 288,
            y = 192
        },
        ConeHandleAdornment = {
            h = 48,
            w = 48,
            x = 336,
            y = 192
        },
        Configuration = {
            h = 48,
            w = 48,
            x = 384,
            y = 192
        },
        Constant = {
            h = 48,
            w = 48,
            x = 432,
            y = 192
        },
        Constructor = {
            h = 48,
            w = 48,
            x = 480,
            y = 192
        },
        CoreGui = {
            h = 48,
            w = 48,
            x = 528,
            y = 192
        },
        CornerWedgePart = {
            h = 48,
            w = 48,
            x = 576,
            y = 192
        },
        CylinderHandleAdornment = {
            h = 48,
            w = 48,
            x = 624,
            y = 192
        },
        CylindricalConstraint = {
            h = 48,
            w = 48,
            x = 672,
            y = 192
        },
        Decal = {
            h = 48,
            w = 48,
            x = 0,
            y = 240
        },
        DepthOfFieldEffect = {
            h = 48,
            w = 48,
            x = 48,
            y = 240
        },
        Dialog = {
            h = 48,
            w = 48,
            x = 144,
            y = 240
        },
        DialogChoice = {
            h = 48,
            w = 48,
            x = 96,
            y = 240
        },
        DistortionSoundEffect = {
            h = 48,
            w = 48,
            x = 192,
            y = 240
        },
        EchoSoundEffect = {
            h = 48,
            w = 48,
            x = 240,
            y = 240
        },
        EditableImage = {
            h = 48,
            w = 48,
            x = 288,
            y = 240
        },
        EditableMesh = {
            h = 48,
            w = 48,
            x = 336,
            y = 240
        },
        Enum = {
            h = 48,
            w = 48,
            x = 432,
            y = 240
        },
        EnumMember = {
            h = 48,
            w = 48,
            x = 384,
            y = 240
        },
        EqualizerSoundEffect = {
            h = 48,
            w = 48,
            x = 480,
            y = 240
        },
        Event = {
            h = 48,
            w = 48,
            x = 528,
            y = 240
        },
        FaceControls = {
            h = 48,
            w = 48,
            x = 576,
            y = 240
        },
        Field = {
            h = 48,
            w = 48,
            x = 624,
            y = 240
        },
        File = {
            h = 48,
            w = 48,
            x = 672,
            y = 240
        },
        FlangeSoundEffect = {
            h = 48,
            w = 48,
            x = 0,
            y = 288
        },
        Folder = {
            h = 48,
            w = 48,
            x = 48,
            y = 288
        },
        ForceField = {
            h = 48,
            w = 48,
            x = 96,
            y = 288
        },
        Frame = {
            h = 48,
            w = 48,
            x = 144,
            y = 288
        },
        Function = {
            h = 48,
            w = 48,
            x = 192,
            y = 288
        },
        GroundController = {
            h = 48,
            w = 48,
            x = 240,
            y = 288
        },
        Handles = {
            h = 48,
            w = 48,
            x = 288,
            y = 288
        },
        HapticService = {
            h = 48,
            w = 48,
            x = 336,
            y = 288
        },
        HeightmapImporterService = {
            h = 48,
            w = 48,
            x = 384,
            y = 288
        },
        Highlight = {
            h = 48,
            w = 48,
            x = 432,
            y = 288
        },
        HingeConstraint = {
            h = 48,
            w = 48,
            x = 480,
            y = 288
        },
        Humanoid = {
            h = 48,
            w = 48,
            x = 576,
            y = 288
        },
        HumanoidDescription = {
            h = 48,
            w = 48,
            x = 528,
            y = 288
        },
        IKControl = {
            h = 48,
            w = 48,
            x = 624,
            y = 288
        },
        ImageButton = {
            h = 48,
            w = 48,
            x = 672,
            y = 288
        },
        ImageHandleAdornment = {
            h = 48,
            w = 48,
            x = 0,
            y = 336
        },
        ImageLabel = {
            h = 48,
            w = 48,
            x = 48,
            y = 336
        },
        Interface = {
            h = 48,
            w = 48,
            x = 96,
            y = 336
        },
        Keyword = {
            h = 48,
            w = 48,
            x = 144,
            y = 336
        },
        Lighting = {
            h = 48,
            w = 48,
            x = 192,
            y = 336
        },
        LineHandleAdornment = {
            h = 48,
            w = 48,
            x = 240,
            y = 336
        },
        LocalFile = {
            h = 48,
            w = 48,
            x = 288,
            y = 336
        },
        LocalScript = {
            h = 48,
            w = 48,
            x = 336,
            y = 336
        },
        LocalizationService = {
            h = 48,
            w = 48,
            x = 384,
            y = 336
        },
        LocalizationTable = {
            h = 48,
            w = 48,
            x = 432,
            y = 336
        },
        MaterialService = {
            h = 48,
            w = 48,
            x = 480,
            y = 336
        },
        MaterialVariant = {
            h = 48,
            w = 48,
            x = 528,
            y = 336
        },
        MemoryStoreService = {
            h = 48,
            w = 48,
            x = 576,
            y = 336
        },
        MeshPart = {
            h = 48,
            w = 48,
            x = 624,
            y = 336
        },
        Meshparts = {
            h = 48,
            w = 48,
            x = 672,
            y = 336
        },
        MessagingService = {
            h = 48,
            w = 48,
            x = 0,
            y = 384
        },
        Method = {
            h = 48,
            w = 48,
            x = 48,
            y = 384
        },
        Model = {
            h = 48,
            w = 48,
            x = 96,
            y = 384
        },
        Modelgroups = {
            h = 48,
            w = 48,
            x = 144,
            y = 384
        },
        Module = {
            h = 48,
            w = 48,
            x = 240,
            y = 384
        },
        ModuleScript = {
            h = 48,
            w = 48,
            x = 192,
            y = 384
        },
        Motor6D = {
            h = 48,
            w = 48,
            x = 288,
            y = 384
        },
        NetworkClient = {
            h = 48,
            w = 48,
            x = 336,
            y = 384
        },
        NoCollisionConstraint = {
            h = 48,
            w = 48,
            x = 384,
            y = 384
        },
        Operator = {
            h = 48,
            w = 48,
            x = 432,
            y = 384
        },
        PackageLink = {
            h = 48,
            w = 48,
            x = 480,
            y = 384
        },
        Pants = {
            h = 48,
            w = 48,
            x = 528,
            y = 384
        },
        Part = {
            h = 48,
            w = 48,
            x = 576,
            y = 384
        },
        PathfindingLink = {
            h = 48,
            w = 48,
            x = 624,
            y = 384
        },
        PathfindingModifier = {
            h = 48,
            w = 48,
            x = 672,
            y = 384
        },
        PathfindingService = {
            h = 48,
            w = 48,
            x = 0,
            y = 432
        },
        PitchShiftSoundEffect = {
            h = 48,
            w = 48,
            x = 48,
            y = 432
        },
        Place = {
            h = 48,
            w = 48,
            x = 96,
            y = 432
        },
        Plane = {
            h = 48,
            w = 48,
            x = 144,
            y = 432
        },
        Players = {
            h = 48,
            w = 48,
            x = 192,
            y = 432
        },
        PluginGuiService = {
            h = 48,
            w = 48,
            x = 240,
            y = 432
        },
        PrismaticConstraint = {
            h = 48,
            w = 48,
            x = 288,
            y = 432
        },
        Property = {
            h = 48,
            w = 48,
            x = 336,
            y = 432
        },
        ProximityPrompt = {
            h = 48,
            w = 48,
            x = 384,
            y = 432
        },
        PublishService = {
            h = 48,
            w = 48,
            x = 432,
            y = 432
        },
        Reference = {
            h = 48,
            w = 48,
            x = 480,
            y = 432
        },
        RemoteEvent = {
            h = 48,
            w = 48,
            x = 528,
            y = 432
        },
        RemoteFunction = {
            h = 48,
            w = 48,
            x = 576,
            y = 432
        },
        RenderingTest = {
            h = 48,
            w = 48,
            x = 624,
            y = 432
        },
        ReplicatedFirst = {
            h = 48,
            w = 48,
            x = 672,
            y = 432
        },
        ReplicatedScriptService = {
            h = 48,
            w = 48,
            x = 0,
            y = 480
        },
        ReplicatedStorage = {
            h = 48,
            w = 48,
            x = 48,
            y = 480
        },
        ReverbSoundEffect = {
            h = 48,
            w = 48,
            x = 96,
            y = 480
        },
        RigidConstraint = {
            h = 48,
            w = 48,
            x = 144,
            y = 480
        },
        RobloxPluginGuiService = {
            h = 48,
            w = 48,
            x = 192,
            y = 480
        },
        RocketPropulsion = {
            h = 48,
            w = 48,
            x = 240,
            y = 480
        },
        RodConstraint = {
            h = 48,
            w = 48,
            x = 288,
            y = 480
        },
        RopeConstraint = {
            h = 48,
            w = 48,
            x = 336,
            y = 480
        },
        ScreenGui = {
            h = 48,
            w = 48,
            x = 384,
            y = 480
        },
        Script = {
            h = 48,
            w = 48,
            x = 432,
            y = 480
        },
        ScrollingFrame = {
            h = 48,
            w = 48,
            x = 480,
            y = 480
        },
        Seat = {
            h = 48,
            w = 48,
            x = 528,
            y = 480
        },
        Selected_Workspace = {
            h = 48,
            w = 48,
            x = 576,
            y = 480
        },
        SelectionBox = {
            h = 48,
            w = 48,
            x = 624,
            y = 480
        },
        SelectionSphere = {
            h = 48,
            w = 48,
            x = 672,
            y = 480
        },
        ServerScriptService = {
            h = 48,
            w = 48,
            x = 0,
            y = 528
        },
        ServerStorage = {
            h = 48,
            w = 48,
            x = 48,
            y = 528
        },
        Shirt = {
            h = 48,
            w = 48,
            x = 144,
            y = 528
        },
        ShirtGraphic = {
            h = 48,
            w = 48,
            x = 96,
            y = 528
        },
        SkinnedMeshPart = {
            h = 48,
            w = 48,
            x = 192,
            y = 528
        },
        Sky = {
            h = 48,
            w = 48,
            x = 240,
            y = 528
        },
        Snap = {
            h = 48,
            w = 48,
            x = 288,
            y = 528
        },
        Snippet = {
            h = 48,
            w = 48,
            x = 336,
            y = 528
        },
        SocialService = {
            h = 48,
            w = 48,
            x = 384,
            y = 528
        },
        Sound = {
            h = 48,
            w = 48,
            x = 576,
            y = 528
        },
        SoundEffect = {
            h = 48,
            w = 48,
            x = 432,
            y = 528
        },
        SoundGroup = {
            h = 48,
            w = 48,
            x = 480,
            y = 528
        },
        SoundService = {
            h = 48,
            w = 48,
            x = 528,
            y = 528
        },
        SpawnLocation = {
            h = 48,
            w = 48,
            x = 624,
            y = 528
        },
        SpecialMesh = {
            h = 48,
            w = 48,
            x = 672,
            y = 528
        },
        SphereHandleAdornment = {
            h = 48,
            w = 48,
            x = 0,
            y = 576
        },
        SpringConstraint = {
            h = 48,
            w = 48,
            x = 48,
            y = 576
        },
        StandalonePluginScripts = {
            h = 48,
            w = 48,
            x = 96,
            y = 576
        },
        StarterCharacterScripts = {
            h = 48,
            w = 48,
            x = 144,
            y = 576
        },
        StarterGui = {
            h = 48,
            w = 48,
            x = 192,
            y = 576
        },
        StarterPack = {
            h = 48,
            w = 48,
            x = 240,
            y = 576
        },
        StarterPlayer = {
            h = 48,
            w = 48,
            x = 336,
            y = 576
        },
        StarterPlayerScripts = {
            h = 48,
            w = 48,
            x = 288,
            y = 576
        },
        Struct = {
            h = 48,
            w = 48,
            x = 384,
            y = 576
        },
        SunRaysEffect = {
            h = 48,
            w = 48,
            x = 432,
            y = 576
        },
        SurfaceAppearance = {
            h = 48,
            w = 48,
            x = 480,
            y = 576
        },
        SurfaceGui = {
            h = 48,
            w = 48,
            x = 528,
            y = 576
        },
        SurfaceSelection = {
            h = 48,
            w = 48,
            x = 576,
            y = 576
        },
        SwimController = {
            h = 48,
            w = 48,
            x = 624,
            y = 576
        },
        Team = {
            h = 48,
            w = 48,
            x = 672,
            y = 576
        },
        Teams = {
            h = 48,
            w = 48,
            x = 0,
            y = 624
        },
        Terrain = {
            h = 48,
            w = 48,
            x = 96,
            y = 624
        },
        TerrainDetail = {
            h = 48,
            w = 48,
            x = 48,
            y = 624
        },
        TestService = {
            h = 48,
            w = 48,
            x = 144,
            y = 624
        },
        TextBox = {
            h = 48,
            w = 48,
            x = 240,
            y = 624
        },
        TextBoxService = {
            h = 48,
            w = 48,
            x = 192,
            y = 624
        },
        TextButton = {
            h = 48,
            w = 48,
            x = 288,
            y = 624
        },
        TextChannel = {
            h = 48,
            w = 48,
            x = 336,
            y = 624
        },
        TextChatCommand = {
            h = 48,
            w = 48,
            x = 384,
            y = 624
        },
        TextChatService = {
            h = 48,
            w = 48,
            x = 432,
            y = 624
        },
        TextLabel = {
            h = 48,
            w = 48,
            x = 480,
            y = 624
        },
        TextString = {
            h = 48,
            w = 48,
            x = 528,
            y = 624
        },
        Texture = {
            h = 48,
            w = 48,
            x = 576,
            y = 624
        },
        Tool = {
            h = 48,
            w = 48,
            x = 624,
            y = 624
        },
        TorsionSpringConstraint = {
            h = 48,
            w = 48,
            x = 672,
            y = 624
        },
        TremoloSoundEffect = {
            h = 48,
            w = 48,
            x = 0,
            y = 672
        },
        TrussPart = {
            h = 48,
            w = 48,
            x = 48,
            y = 672
        },
        TypeParameter = {
            h = 48,
            w = 48,
            x = 96,
            y = 672
        },
        UGCValidationService = {
            h = 48,
            w = 48,
            x = 144,
            y = 672
        },
        UIAspectRatioConstraint = {
            h = 48,
            w = 48,
            x = 192,
            y = 672
        },
        UICorner = {
            h = 48,
            w = 48,
            x = 240,
            y = 672
        },
        UIGradient = {
            h = 48,
            w = 48,
            x = 288,
            y = 672
        },
        UIGridLayout = {
            h = 48,
            w = 48,
            x = 336,
            y = 672
        },
        UIListLayout = {
            h = 48,
            w = 48,
            x = 384,
            y = 672
        },
        UIPadding = {
            h = 48,
            w = 48,
            x = 432,
            y = 672
        },
        UIPageLayout = {
            h = 48,
            w = 48,
            x = 480,
            y = 672
        },
        UIScale = {
            h = 48,
            w = 48,
            x = 528,
            y = 672
        },
        UISizeConstraint = {
            h = 48,
            w = 48,
            x = 576,
            y = 672
        },
        UIStroke = {
            h = 48,
            w = 48,
            x = 624,
            y = 672
        },
        UITableLayout = {
            h = 48,
            w = 48,
            x = 672,
            y = 672
        },
        UITextSizeConstraint = {
            h = 48,
            w = 48,
            x = 720,
            y = 0
        },
        Unit = {
            h = 48,
            w = 48,
            x = 720,
            y = 48
        },
        UniversalConstraint = {
            h = 48,
            w = 48,
            x = 720,
            y = 96
        },
        UnreliableRemoteEvent = {
            h = 48,
            w = 48,
            x = 720,
            y = 144
        },
        UpdateAvailable = {
            h = 48,
            w = 48,
            x = 720,
            y = 192
        },
        UserService = {
            h = 48,
            w = 48,
            x = 720,
            y = 240
        },
        VRService = {
            h = 48,
            w = 48,
            x = 720,
            y = 288
        },
        Value = {
            h = 48,
            w = 48,
            x = 720,
            y = 336
        },
        Variable = {
            h = 48,
            w = 48,
            x = 720,
            y = 384
        },
        VehicleSeat = {
            h = 48,
            w = 48,
            x = 720,
            y = 432
        },
        VideoFrame = {
            h = 48,
            w = 48,
            x = 720,
            y = 480
        },
        ViewportFrame = {
            h = 48,
            w = 48,
            x = 720,
            y = 528
        },
        VirtualUser = {
            h = 48,
            w = 48,
            x = 720,
            y = 576
        },
        VoiceChannel = {
            h = 48,
            w = 48,
            x = 720,
            y = 624
        },
        VoiceChatService = {
            h = 48,
            w = 48,
            x = 720,
            y = 672
        },
        Voicechat = {
            h = 48,
            w = 48,
            x = 0,
            y = 720
        },
        WedgePart = {
            h = 48,
            w = 48,
            x = 48,
            y = 720
        },
        Weld = {
            h = 48,
            w = 48,
            x = 144,
            y = 720
        },
        WeldConstraint = {
            h = 48,
            w = 48,
            x = 96,
            y = 720
        },
        Wire = {
            h = 48,
            w = 48,
            x = 192,
            y = 720
        },
        WireframeHandleAdornment = {
            h = 48,
            w = 48,
            x = 240,
            y = 720
        },
        Workspace = {
            h = 48,
            w = 48,
            x = 288,
            y = 720
        },
        WorldModel = {
            h = 48,
            w = 48,
            x = 336,
            y = 720
        },
        WrapLayer = {
            h = 48,
            w = 48,
            x = 384,
            y = 720
        },
        WrapTarget = {
            h = 48,
            w = 48,
            x = 432,
            y = 720
        }
    }
};