-- Decompiled with Potassium's decompiler.

local v1 = {
    at = require(script.at),
    concat = require(script.concat),
    concatDeep = require(script.concatDeep),
    copy = require(script.copy),
    copyDeep = require(script.copyDeep),
    count = require(script.count),
    create = require(script.create),
    dedupe = require(script.dedupe),
    difference = require(script.difference),
    differenceSymmetric = require(script.differenceSymmetric),
    equals = require(script.equals),
    equalsDeep = require(script.equalsDeep),
    every = require(script.every),
    filter = require(script.filter),
    find = require(script.find),
    findLast = require(script.findLast),
    findWhere = require(script.findWhere),
    findWhereLast = require(script.findWhereLast),
    first = require(script.first),
    flatten = require(script.flatten),
    freeze = require(script.freeze),
    freezeDeep = require(script.freezeDeep),
    includes = require(script.includes),
    insert = require(script.insert),
    is = require(script.is),
    last = require(script.last),
    map = require(script.map),
    pop = require(script.pop),
    push = require(script.push),
    reduce = require(script.reduce),
    reduceRight = require(script.reduceRight),
    removeIndex = require(script.removeIndex),
    removeIndices = require(script.removeIndices),
    removeValue = require(script.removeValue),
    removeValues = require(script.removeValues),
    reverse = require(script.reverse),
    set = require(script.set),
    shift = require(script.shift),
    shuffle = require(script.shuffle),
    slice = require(script.slice),
    some = require(script.some),
    sort = require(script.sort),
    splice = require(script.splice),
    toSet = require(script.toSet),
    unshift = require(script.unshift),
    update = require(script.update),
    zip = require(script.zip),
    zipAll = require(script.zipAll)
};
v1.join = v1.concat;
v1.merge = v1.concat;
v1.joinDeep = v1.concatDeep;
v1.mergeDeep = v1.concatDeep;
v1.append = v1.push;
v1.prepend = v1.unshift;
v1.indexOf = v1.find;
v1.has = v1.includes;
v1.contains = v1.includes;
v1.isArray = v1.is;

return v1;