-- CorePackages.Workspace.Packages._Workspace.TnSAvatarIdentification.TnSAvatarIdentification.Flags.GetFIntReportAnythingAvatarIdentificationCloseDiscardDistanceHundredths
-- Script path: CorePackages.Workspace.Packages._Workspace.TnSAvatarIdentification.TnSAvatarIdentification.Flags.GetFIntReportAnythingAvatarIdentificationCloseDiscardDistanceHundredths
-- Decompile time: 0.06 ms

Failed to decode Luau bytecode: Unsupported bytecode version 29