-- CorePackages.Workspace.Packages._Workspace.TnSAvatarIdentification.TnSAvatarIdentification.Flags.GetFIntReportAnythingAvatarIdentificationDiscardFractionSkipThresholdPercent
-- Script path: CorePackages.Workspace.Packages._Workspace.TnSAvatarIdentification.TnSAvatarIdentification.Flags.GetFIntReportAnythingAvatarIdentificationDiscardFractionSkipThresholdPercent
-- Decompile time: 0.05 ms

Failed to decode Luau bytecode: Unsupported bytecode version 29