-- CorePackages.Workspace.Packages._Workspace.TnSAvatarIdentification.TnSAvatarIdentification.Flags.GetFIntReportAnythingAvatarIdentificationOffScreenDiscardDistancePercent
-- Script path: CorePackages.Workspace.Packages._Workspace.TnSAvatarIdentification.TnSAvatarIdentification.Flags.GetFIntReportAnythingAvatarIdentificationOffScreenDiscardDistancePercent
-- Decompile time: 0.04 ms

Failed to decode Luau bytecode: Unsupported bytecode version 29