-- ReplicatedStorage.Packages.DebugTools.Client.Vendor.ClassIndex.init.spec
-- Script path: ReplicatedStorage.Packages.DebugTools.Client.Vendor.ClassIndex.init.spec
-- Decompile time: 1.23 ms

return function() -- Line: 1
    local Parent = require(script.Parent)
    it("Should be able to access the raw API dump", function() -- Line: 4 -- upvalues: Parent (val)
        local v1 = Parent.FetchApiDump()
        expect(v1).never.to.equal(nil)
        expect(v1.Classes).never.to.equal(nil)
        expect(v1.Version).never.to.equal(nil)
    end)
    it("Should be able to fetch all classes from the raw API dump", function() -- Line: 12 -- upvalues: Parent (val)
        local v1 = Parent.FetchAllClasses()
        expect(#v1).never.to.equal(0)
        expect(table.find(v1, "Workspace")).never.to.equal(nil)
    end)
    it("Should be able to query class names", function() -- Line: 19 -- upvalues: Parent (val)
        expect(Parent.IsClassRegistered("Workspace")).to.equal(true)
        expect(Parent.IsClassRegistered("FakeWorkspace")).to.equal(false)
    end)
    it("Should be able to query class members", function() -- Line: 24 -- upvalues: Parent (val)
        local Workspace = Parent.FetchClassMembers("Workspace")
        expect(#Workspace).never.to.equal(0)
        for i, j in Workspace do
            expect(workspace[j]).never.to.equal(nil)
        end
    end)
    it("Should be able to fetch the member type from a class", function() -- Line: 34 -- upvalues: Parent (val)
        local v1 = Parent.FetchClassMemberType("Workspace", "Gravity")
        expect(v1).to.equal("Property")
    end)
    it("Should be able to fetch the tags for a member of a class", function() -- Line: 40 -- upvalues: Parent (val)
        local v1 = Parent.FetchClassMemberTags("Workspace", "StreamingMinRadius")
        expect(v1.NotScriptable).to.equal(true)
    end)
    it("Should be able to fetch the security for a member of a class", function() -- Line: 46 -- upvalues: Parent (val)
        local v1 = Parent.FetchClassMemberSecurity("Workspace", "StreamingEnabled")
        expect(v1.Read).to.equal("None")
        expect(v1.Write).to.equal("PluginSecurity")
    end)
    it("Should be able to fetch the thread safety for a member of a class", function() -- Line: 53 -- upvalues: Parent (val)
        local v1 = Parent.FetchClassMemberThreadSafety("Workspace", "StreamingEnabled")
        expect(v1).to.equal("ReadSafe")
    end)
    it("Should be able to query class superclass", function() -- Line: 59 -- upvalues: Parent (val)
        local Workspace = Parent.FetchClassSuperclass("Workspace")
        expect(Workspace).to.equal("WorldRoot")
    end)
    it("Should be able to query class superclasses", function() -- Line: 65 -- upvalues: Parent (val)
        local Workspace = Parent.FetchClassSuperclasses("Workspace")
        expect(#Workspace).never.to.equal(0)
        expect(Workspace[#Workspace]).to.equal("<<<ROOT>>>")
        expect(Workspace[1]).to.equal("WorldRoot")
    end)
end