-- ReplicatedStorage.Components.Common.VFXLibary.CreateImpact.Components.Materials
-- Script path: ReplicatedStorage.Components.Common.VFXLibary.CreateImpact.Components.Materials
-- Decompile time: 0.19 ms

return table.freeze({
    Asphalt = "Ground",
    Basalt = "Ground",
    Brick = "Concrete",
    Cobblestone = "Ground",
    Concrete = "Concrete",
    CrackedLava = "Ground",
    DiamondPlate = "Metal",
    CorrodedMetal = "Metal",
    Fabric = "Fabric",
    Foil = "Metal",
    Glacier = "Ground",
    Glass = "Glass",
    Granite = "Concrete",
    Grass = "Ground",
    Ground = "Ground",
    Ice = "Ground",
    LeafyGrass = "Ground",
    Limestone = "Concrete",
    Marble = "Concrete",
    Metal = "Metal",
    Mud = "Ground",
    Pavement = "Ground",
    Plastic = "Ground",
    Rock = "Concrete",
    Salt = "Ground",
    Sand = "Ground",
    Sandstone = "Ground",
    Slate = "Concrete",
    SmoothPlastic = "Ground",
    Snow = "Ground",
    Wood = "Wood",
    WoodPlanks = "Wood",
    ForceField = "Metal",
    Neon = "Glass",
})