-- CorePackages.Workspace.Packages._Index.AvatarExperienceProfilePictureEditor.AvatarExperienceProfilePictureEditor.Components.EditProfileImage.useRotatableAvatarPreviewViewModel
-- Script path: CorePackages.Workspace.Packages._Index.AvatarExperienceProfilePictureEditor.AvatarExperienceProfilePictureEditor.Components.EditProfileImage.useRotatableAvatarPreviewViewModel
-- Decompile time: 0.07 ms

Failed to decode Luau bytecode: Unsupported bytecode version 29